# [ INDEXES ] #
# Collect enums that are not usually required by the game data, but allow for easier
# understanding of content to developers and players
import std/enumutils
import std/bitops

type
  MWClothType* = enum
    Pants      = 0
    Shoes      = 1
    Shirt      = 2
    Belt       = 3
    Robe       = 4
    RightGlove = 5
    LeftGlove  = 6
    Skirt      = 7
    Ring       = 8
    Amulet     = 9
  MWArmorType* = enum
    Helmet        = 0
    Cuirass       = 1
    LeftPauldron  = 2
    RightPauldron = 3
    Greaves       = 4
    Boots         = 5
    LeftGauntlet  = 6
    RightGauntlet = 7
    Shield        = 8
    LeftBracer    = 9
    RightBracer   = 10
  MWBipedType* = enum
    Head          = 1
    Hair          = 2
    Cuirass       = 3
    Groin         = 4
    Skirt         = 5
    RightHand     = 6
    LeftHang      = 7
    RightWrist    = 8
    LeftWrist     = 9
    Shield        = 10
    RightForearm  = 11
    LeftForearm   = 12
    RightUpperArm = 13
    LeftUpperArm  = 14
    RightFoot     = 15
    LeftFoot      = 16
    RightAnkle    = 17
    LeftAnkle     = 18
    RightKnee     = 19
    LeftKnee      = 20
    RightUpperLeg = 21
    LeftUpperLeg  = 22
    RightPauldron = 23
    LeftPauldron  = 24
    Weapon        = 25
    Tail          = 26
  MWEffectType* = enum
    sEffectWaterBreathing           = 0
    sEffectSwiftSwim                = 1
    sEffectWaterWalking             = 2
    sEffectShield                   = 3
    sEffectFireShield               = 4
    sEffectLightningShield          = 5
    sEffectFrostShield              = 6
    sEffectBurden                   = 7
    sEffectFeather                  = 8
    sEffectJump                     = 9
    sEffectLevitate                 = 10
    sEffectSlowFall                 = 11
    sEffectLock                     = 12
    sEffectOpen                     = 13
    sEffectFireDamage               = 14
    sEffectShockDamage              = 15
    sEffectFrostDamage              = 16
    sEffectDrainAttribute           = 17
    sEffectDrainHealth              = 18
    sEffectDrainSpellpoints         = 19
    sEffectDrainFatigue             = 20
    sEffectDrainSkill               = 21
    sEffectDamageAttribute          = 22
    sEffectDamageHealth             = 23
    sEffectDamageMagicka            = 24
    sEffectDamageFatigue            = 25
    sEffectDamageSkill              = 26
    sEffectPoison                   = 27
    sEffectWeaknessToFire           = 28
    sEffectWeaknessToFrost          = 29
    sEffectWeaknessToShock          = 30
    sEffectWeaknessToMagicka        = 31
    sEffectWeaknessToCommonDisease  = 32
    sEffectWeaknessToBlightDisease  = 33
    sEffectWeaknessToCorprusDisease = 34
    sEffectWeaknessToPoison         = 35
    sEffectWeaknessToNormalWeapons  = 36
    sEffectDisintegrateWeapon       = 37
    sEffectDisintegrateArmor        = 38
    sEffectInvisibility             = 39
    sEffectChameleon                = 40
    sEffectLight                    = 41
    sEffectSanctuary                = 42
    sEffectNightEye                 = 43
    sEffectCharm                    = 44
    sEffectParalyze                 = 45
    sEffectSilence                  = 46
    sEffectBlind                    = 47
    sEffectSound                    = 48
    sEffectCalmHumanoid             = 49
    sEffectCalmCreature             = 50
    sEffectFrenzyHumanoid           = 51
    sEffectFrenzyCreature           = 52
    sEffectDemoralizeHumanoid       = 53
    sEffectDemoralizeCreature       = 54
    sEffectRallyHumanoid            = 55
    sEffectRallyCreature            = 56
    sEffectDispel                   = 57
    sEffectSoultrap                 = 58
    sEffectTelekinesis              = 59
    sEffectMark                     = 60
    sEffectRecall                   = 61
    sEffectDivineIntervention       = 62
    sEffectAlmsiviIntervention      = 63
    sEffectDetectAnimal             = 64
    sEffectDetectEnchantment        = 65
    sEffectDetectKey                = 66
    sEffectSpellAbsorption          = 67
    sEffectReflect                  = 68
    sEffectCureCommonDisease        = 69
    sEffectCureBlightDisease        = 70
    sEffectCureCorprusDisease       = 71
    sEffectCurePoison               = 72
    sEffectCureParalyzation         = 73
    sEffectRestoreAttribute         = 74
    sEffectRestoreHealth            = 75
    sEffectRestoreSpellPoints       = 76
    sEffectRestoreFatigue           = 77
    sEffectRestoreSkill             = 78
    sEffectFortifyAttribute         = 79
    sEffectFortifyHealth            = 80
    sEffectFortifySpellpoints       = 81
    sEffectFortifyFatigue           = 82
    sEffectFortifySkill             = 83
    sEffectFortifyMagickaMultiplier = 84
    sEffectAbsorbAttribute          = 85
    sEffectAbsorbHealth             = 86
    sEffectAbsorbSpellPoints        = 87
    sEffectAbsorbFatigue            = 88
    sEffectAbsorbSkill              = 89
    sEffectResistFire               = 90
    sEffectResistFrost              = 91
    sEffectResistShock              = 92
    sEffectResistMagicka            = 93
    sEffectResistCommonDisease      = 94
    sEffectResistBlightDisease      = 95
    sEffectResistCorprusDisease     = 96
    sEffectResistPoison             = 97
    sEffectResistNormalWeapons      = 98
    sEffectResistParalysis          = 99
    sEffectRemoveCurse              = 100
    sEffectTurnUndead               = 101
    sEffectSummonScamp              = 102
    sEffectSummonClannfear          = 103
    sEffectSummonDaedroth           = 104
    sEffectSummonDremora            = 105
    sEffectSummonAncestralGhost     = 106
    sEffectSummonSkeletalMinion     = 107
    sEffectSummonLeastBonewalker    = 108
    sEffectSummonGreaterBonewalker  = 109
    sEffectSummonBonelord           = 110
    sEffectSummonWingedTwilight     = 111
    sEffectSummonHunger             = 112
    sEffectSummonGoldensaint        = 113
    sEffectSummonFlameAtronach      = 114
    sEffectSummonFrostAtronach      = 115
    sEffectSummonStormAtronach      = 116
    sEffectFortifyAttackBonus       = 117
    sEffectCommandCreatures         = 118
    sEffectCommandHumanoids         = 119
    sEffectBoundDagger              = 120
    sEffectBoundLongsword           = 121
    sEffectBoundMace                = 122
    sEffectBoundBattleAxe           = 123
    sEffectBoundSpear               = 124
    sEffectBoundLongbow             = 125
    sEffectExtraSpell               = 126
    sEffectBoundCuirass             = 127
    sEffectBoundHelm                = 128
    sEffectBoundBoots               = 129
    sEffectBoundShield              = 130
    sEffectBoundGloves              = 131
    sEffectCorpus                   = 132
    sEffectVampirism                = 133
    sEffectSummonCenturionSphere    = 134
    sEffectSunDamage                = 135
    sEffectStuntedMagicka           = 136
    sEffectSummonFabricant          = 137 # TR
    sEffectSummonCreature01         = 138 # Call Wolf (BM)
    sEffectSummonCreature02         = 139 # Call Bear (BM)
    sEffectSummonCreature03         = 140 # Call Bonewolf (BM)
    sEffectSummonCreature04         = 141 # BM/TR
    sEffectSummonCreature05         = 142 # BM/TR
  MWLightType* = enum
    Dynamic      = 1
    CanCarry     = 2
    Negative     = 4
    Flicker      = 8
    Fire         = 10
    OffByDefault = 20
    FlickerSlow  = 40
    Pulse        = 80
    PulseSlow    = 100
  MWWeaponType* = enum
    ShortBladeOneHand = 0
    LongBladeOneHand  = 1
    LongBladeTwoClose = 2
    BluntOneHand      = 3
    BluntTwoClose     = 4
    BluntTwoWide      = 5
    SpearTwoWide      = 6
    AxeOneHand        = 7
    AxeTwoHand        = 8
    MarksmanBow       = 9
    MarksmanCrossbow  = 10
    MarksmanThrown    = 11
    Arrow             = 12
  MWWeaponFlags* = enum
    IgnoreNormalWeaponResistance = 1
    Silver                       = 2
  MWContainerFlags* = enum
    Organic  = 1 # 0x1
    Respawns = 2 # 0x2 | organic only
    Unknown  = 8 # 0x8 | always set
  MWLightFlags* = enum
    Dynamic      = 1   # 0x0001
    CanCarry     = 2   # 0x0002
    Negative     = 4   # 0x0004
    Flicker      = 8   # 0x0008
    Fire         = 16  # 0x0010
    OffByDefault = 32  # 0x0020
    FlickerSlow  = 64  # 0x0040
    Pulse        = 128 # 0x0080
    PulseSlow    = 256 # 0x0100
  MWApparatusType* = enum
    MortarAndPestle = 0
    Alembic         = 1
    Calcinator      = 2
    Retort          = 3
  MWAttributeType* = enum
    None         = -1
    Strength     = 0
    Intelligence = 1
    Willpower    = 2
    Agility      = 3
    Speed        = 4
    Endurance    = 5
    Personality  = 6
    Luck         = 7
  MWSkillType* = enum
    None        = -1
    Block       = 0
    Armorer     = 1
    MediumArmor = 2
    HeavyArmor  = 3
    BluntWeapon = 4
    LongBlade   = 5
    Axe         = 6
    Spear       = 7
    Athletics   = 8
    Enchant     = 9
    Destruction = 10
    Alteration  = 11
    Illusion    = 12
    Conjuration = 13
    Mysticism   = 14
    Restoration = 15
    Alchemy     = 16
    Unarmored   = 17
    Security    = 18
    Sneak       = 19
    Acrobatics  = 20
    LightArmor  = 21
    ShortBlade  = 22
    Marksman    = 23
    Mercantile  = 24
    Speechcraft = 25
    HandToHand  = 26
  MWSpecialisationType* = enum
    Combat  = 0
    Magic   = 1
    Stealth = 2
  MWServicesTradesType* = enum # originally represented as hexadecimals
    Weapon      = 1'u32      # 0x00001 | trades
    Armor       = 2'u32      # 0x00002
    Clothing    = 4'u32      # 0x00004
    Books       = 8'u32      # 0x00008
    Ingredients = 16'u32     # 0x00010
    Picks       = 32'u32     # 0x00020
    Probes      = 64'u32     # 0x00040
    Lights      = 128'u32    # 0x00080
    Apparatus   = 256'u32    # 0x00100
    RepairItems = 512'u32    # 0x00200
    Misc        = 1024'u32   # 0x00400
    Spells      = 2048'u32   # 0x00800
    MagicItems  = 4096'u32   # 0x01000
    Potions     = 8192'u32   # 0x02000
    Training    = 16384'u32  # 0x04000 | services
    Spellmaking = 32768'u32  # 0x08000
    Enchanting  = 65536'u32  # 0x10000
    # TODO: Repair      = 131072'u32 # 0x20000
  MWBodyPartType* = enum
    Head     = 0
    Hair     = 1
    Neck     = 2
    Chest    = 3
    Groin    = 4
    Hand     = 5
    Wrist    = 6
    Forearm  = 7
    Upperarm = 8
    Foot     = 9
    Ankle    = 10
    Knee     = 11
    Upperleg = 12
    Clavicle = 13
    Tail     = 14
  MWBodyKindType* = enum
    Skin     = 0
    Clothing = 1
    Armor    = 2
  MWBodyFlags* = enum
    NPCMale   = 0 # non-playable
    NPCFemale = 1
    Male      = 2 # playable
    Female    = 3
  MWRaceFlags* = enum
    NonplayableHumanLike = 0
    PlayableHumanLike    = 1
    NonplayableBeast     = 2
    PlayableBeast        = 3
  MWMagicSchoolType* = enum
    Alteration  = 0
    Conjuration = 1
    Destruction = 2
    Illusion    = 3
    Mysticism   = 4
    Restoration = 5
  MWMagicEffectFlags* = enum
    TargetsSkill     = 1'u32      # 0x00001
    TargetsAttribute = 2'u32      # 0x00002
    NoDuration       = 4'u32      # 0x00004
    NoMagnitude      = 8'u32      # 0x00008
    Harmful          = 16'u32     # 0x00010
    ContinuousVFX    = 32'u32     # 0x00020
    CanCastOnSelf    = 64'u32     # 0x00040
    CanCastOnTouch   = 128'u32    # 0x00080
    CanCastOnTarget  = 256'u32    # 0x00100
    Spellmaking      = 512'u32    # 0x00200
    Enchanting       = 1024'u32   # 0x00400
    NegativeLighting = 2048'u32   # 0x00800
    AppliedOnce      = 4096'u32   # 0x01000
    Stealth          = 8192'u32   # 0x02000
    CannotRecast     = 16384'u32  # 0x04000
    IllegalDaedra    = 32768'u32  # 0x08000
    Unreflectable    = 65536'u32  # 0x10000
    # TODO: LinkedToCaster   = 131072'u32 # 0x20000
  MWSpellType* = enum
    Spell   = 0
    Ability = 1
    Blight  = 2
    Disease = 3
    Curse   = 4 # unused
    Power   = 5
  MWSpellDataFlags* = enum
    AutoCalc       = 1 # 0x1
    PCStart        = 2 # 0x2
    AlwaysSucceeds = 4 # 0x4
  MWEnchantmentType* = enum
    CastOnce       = 0
    CastStrikes    = 1
    CastWhenUsed   = 2
    ConstantEffect = 3
  MWEnchantmentRange* = enum
    Self   = 0
    Touch  = 1
    Target = 2
  MWSoundGeneratorType* = enum
    LeftFoot  = 0
    RightFoot = 1
    SwimLeft  = 2
    SwimRight = 3
    Moan      = 4
    Roar      = 5
    Scream    = 6
    Land      = 7
  MWCreatureType* = enum
    Creature = 0
    Daedra   = 1
    Undead   = 2
    Humanoid = 3
  MWNPCFlags* = enum
    Female        = 1    # 0x0001
    Essential     = 2    # 0x0002
    Respawn       = 4    # 0x0004
    Unknown       = 8    # 0x0008 | Always true
    Autocalc      = 16   # 0x0010
    BloodSkeleton = 1024 # 0x0400 | Blood Texture: Skeleton
    BloodMetal    = 2048 # 0x0800 | Blood Texture: Metal Sparks
  MWCellFlags* = enum
    Interior       = 1   # 0x01
    HasWater       = 2   # 0x02
    IllegalToSleep = 4   # 0x04
    BehaveLikeExt  = 128 # 0x80

const SERVICES* = [Training, Spellmaking, Enchanting]

type
  FieldType* = enum
    Float = 'f'
    Long  = 'l'
    Short = 's'

proc yieldServicesTrades* (flags: uint32): seq[MWServicesTradesType] =
  for mi in MWServicesTradesType:
    if uint32(mi.ord) == bitand(uint32(mi.ord), flags): # check if 'mi' is within 'flags'
      result.add(mi)

proc checkFlagsData* [T, I](flags: I): seq[T] =
  # abstracted proc to check what enum values are hold in `flags` value
  # T = enum type
  # I = type casted/checked value against
  for mi in T.items():
    if cast[I](mi.ord) == bitand(cast[I](mi.ord), flags): # check if enum item (mi) is within 'flags'
      result.add(mi)